# Generated by Django 3.0.5 on 2023-04-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_user_registration_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration_model',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
