# Generated by Django 3.0.5 on 2023-05-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20230427_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='current_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
