# Generated by Django 3.0.5 on 2023-05-15 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_post_current_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_registration_model',
        ),
    ]
