# Generated by Django 3.0.5 on 2023-05-17 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_user_registration_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_registration_model',
        ),
    ]
