# Generated by Django 3.0.5 on 2023-05-18 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('app1', '0008_custom_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='custom_user',
        ),
    ]
