# Generated by Django 3.0.5 on 2023-06-06 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_transaction_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='transaction_model',
        ),
    ]
