# Generated by Django 3.0.5 on 2023-06-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_transaction_tracking_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_tracking_model',
            name='address',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='transaction_tracking_model',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
    ]
