# Generated by Django 3.0.5 on 2023-06-12 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_auto_20230609_1105'),
    ]

    operations = [
        migrations.DeleteModel(
            name='transaction_tracking_model',
        ),
    ]
